project:
  type: website

website:
  title: "新女神転生"
  navbar:
    left:
      - text: "Project Proposal"
        href: index.qmd
      - text: "Methodology"
        menu: # This indicates a dropdown menu
          - text: "Data Collection"
            href: methodology_data_collection.qmd
          - text: "Data Preparation"
            href: methodology_data_preparation.qmd
      - text: "Analysis & Results"
        menu: # This indicates a dropdown menu
          - text: "Preparing and Identifying of Potential Sites"
            href: methodology_site_identification.qmd
          - text: "Solar Farm Estimations and Calculations"
            href: solar_farm_calculations.qmd
      - text: "Lessons Learnt"
        href: lessons_learnt.qmd
      - text: "Poster"
        href: poster.qmd
      - text: "About"
        href: about.qmd
  sidebar:
    title: "On this page"
    contents:
      - Project Motivation
      - Project Objectives
      - Scope of Work
      - Project Schedule (Gantt Chart)

format:
  html:
    theme: minty # Or choose a different theme
    css: styles.css  # If you have custom CSS
    page-layout: full # Correct placement