project:
  type: website

website:
  title: "SMT201 Project"
  navbar:
    left:
      - text :"overviewww"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Abowwwut
