# Lessons Learnt

##  Challenges We faced
Gathering hard geographical visualization data to justify our points proved to be rather difficult. A lot of reliable, accessible geographical data was paywalled under ARCGis, so we had to find workarounds for that, while ensuring the same level of firsthand accuracy that we aspired to. This is why we resorted using the USGS Earthfinder to find specific raster maps for conversion, as well as using NASA's POWER project, which while reliable, was a somewhat esoteric data source, specifically when it came to an aspect like solar irradiation, where figures are quoted, but specific, detailed sourcing proved hard to find. 

Singapore particularly proved to be somewhat challenging to really build an interesting case study around. Much of the available geographical data, most of which was in the raster format, failed to capture existing geographical variations within Singapore, given their lower resolution. The one exception was the USGS topography data. Additionally, Singapore itself lacks the temperature or irradiation variance to meaningfully provide any justifications to build farms in one area over another.

## Future Work
* Explore the possibility of building installations on the rooftops of industrial buildings, seeing that Singapore has a significant proportion of land being occupied by industrial installations.
* Go more in depth into agrivoltaics, more precisely into the infrastructure needed and the measures to be made for the panels to coexist effectively with the existing agricultural infrastructure