<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>solar_farm_calculations – 新女神転生</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bd8cb2610f6c2810c4bc87234a365cf8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">新女神転生</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Project Proposal</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="./methodology_data_collection.html">
 <span class="dropdown-text">Data Collection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./methodology_data_preparation.html">
 <span class="dropdown-text">Data Preparation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis--results" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Analysis &amp; Results</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis--results">    
        <li>
    <a class="dropdown-item" href="./methodology_site_identification.html">
 <span class="dropdown-text">Preparing and Identifying of Potential Sites</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./solar_farm_calculations.html">
 <span class="dropdown-text">Solar Farm Analysis and Calculations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./conclusion.html">
 <span class="dropdown-text">Conclusion</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./lessons_learnt.html"> 
<span class="menu-text">Lessons Learnt</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./poster.html"> 
<span class="menu-text">Poster</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./pages/map.html"> 
<span class="menu-text">Web Map</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="determining-most-viable-area" class="level1">
<h1>Determining Most Viable Area</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_0.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.1</figcaption>
</figure>
</div>
<p>We determined the most viable area as two main subzones: Murai and Lim Chu Kang. They possess one of the largest connected open spaces within Master Plan 2019, which would be hugely beneficial for maximising solar panel placement.</p>
<p>Solar farms can be harmful to the environment, as their construction process disturbs existing migration pathways and can cause soil erosion. As such, we will have a 1km radius buffer zone surrounding these nature reserves whereby the covered land space is deemed unsuitable.</p>
</section>
<section id="analysing-slope-and-aspect" class="level1">
<h1>Analysing Slope and Aspect</h1>
<p>Solar farms benefit from being placed on flat terrain with minimal slope degree. As such, finding areas that already possess a low slope degree would be the most optimal, since there would be no need for terraforming.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_1.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.2</figcaption>
</figure>
</div>
<p>As observed, Lim Chu Kang possesses extremely low slope degrees, making it particularly suitable for solar farm construction. Sarimbun and Murai Reservoir have relatively high slope degree, making them unappealing, whereas Poyan Reservoir’s immediate surrounding land has low slope degree, making it potentially optimal for PV farm construction.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_2.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.3</figcaption>
</figure>
</div>
<p>For aspect data, since Singapore lies on the Northern Hemisphere it would technically benefit from southern topology slopes for placing solar panels due to the way the sun moves during the day. This makes the northern shoreline of Poyan Reservoir somewhat better at collecting sunlight. However, since Singapore is so close to the equator, this benefit is virtually negligible since the sun will be overhead during noon, and while other areas like Lim Chu Kang could be considered to be more ‘suboptimal’, this difference is not a glaring concern.</p>
</section>
<section id="lim-chu-kang" class="level1">
<h1>Lim Chu Kang</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_3.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.4</figcaption>
</figure>
</div>
<p>Even after we accommodate a 1km radius buffer zone for nature reserves in Lim Chu Kang, there is still a sizable amount of space left. This space is largely free, with some areas on the fringes being utilised for agricultural purposes. There is a decent amount of buildings in the area, which could be leveraged for auxiliary purposes in the solar farms (eg. offices, storing inverters, solar farm substations to connect to the main electrical grid).</p>
<p><strong>From the positioning of the internal roads within Lim Chu Kang, we propose the following plan to maximise space for solar panel placement:</strong></p>
<ul>
<li>The area 0-5m from the roads should not have any sort of infrastructure on them. This provides a sort of buffer space, reserved for placement of power lines, drainages, or just as emergency access for vehicles.</li>
<li>5-10m from the roads should be used for vegetation screening, whereby plants are placed on this area range for the express purpose of obstructing wind and dust from striking and potentially wearing away at the solar panels, whilst also maintaining the local aesthetic of the area. Since Singapore is called a ‘Garden City’, maintaining this image and reputation can only be beneficial.</li>
<li>10-15m from the roads is reserved for fencing, which should be a chain-link mesh around 2-2.5 meters in height to deter trespassers, and the fence should be 0.5-1 meter away from the vegetation screening for maintenance access.</li>
<li>15-20m from the roads, behind the fencing, is where drainage swales should be created. These drainages would help to manage and capture runoff from the solar panels, reducing the risk of water damage to the solar panels and damage due to soil erosion affecting the infrastructure’s structural integrity. This is especially important when considering that Singapore has two monsoon seasons.</li>
</ul>
<p>As an additional bonus, there is worth in considering the concept of agrivoltaics, defined as the act of using the same land for both agriculture farming and solar panel placement. Typically, crops or livestock would be situated underneath or adjacent to the solar panels. Considering Singapore’s already limited and quickly shrinking available land space, being able to maximise the efficiency of every square meter of land is vital. Additionally, the presence of the solar panels also provides side benefits: the partial shading provided assists in lowering soil/air temperatures, and also protects the crops from harsh weather conditions.</p>
<p>It should be noted that agricultural projects have already been roadmapped within the Lim Chu Kang area in the past. For instance, in 2020, there were plans to transform Lim Chu Kang into a high-productivity agricultural food zone, as announced by the Singapore Food Agency (SFA), but this plan has since been delayed. This solar farm initiative could assist in reviving the feasibility of this plan, as their long-term sustainability goals align and complement each other.</p>
</section>
<section id="poyan-reservoir" class="level1">
<h1>Poyan Reservoir</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_4.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.5</figcaption>
</figure>
</div>
<p>Poyan Reservoir’s shorelines are of relatively low slope degrees, which makes them optimal for placing supporting infrastructure like inverters or housing substations, with room for more land intensive structures like battery storage arrays, whilst the solar panels themselves can be installed onto a floating platform covering Poyan Reservoir. There is relatively little existing building infrastructure, so that would be one of the shortcomings that has to be addressed if there are any plans to build a solar farm in this area. However, due to the good connectivity of this place, as supported by the placement of road infrastructure, this would make the construction process easier as materials can still be transported without much difficulty.</p>
<p>A potential concern we had was that since Poyan Reservoir technically fell within the boundary area of the Singapore Armed Forces (being within the SAFTI Live Firing Area), that would make installation of a solar farm impossible. However, Tengeh Reservoir also falls within the SAFTI Live Firing Area, and since a solar farm already exists there, we came to the conclusion that there was still potential for Poyan Reservoir to host a solar farm of its own.</p>
<p>Due to the fact that the idea is to have a floating solar farm here, there would be less of a need for drainage swales. Vegetation screening can be considered, but since this area’s road infrastructure is far less concentrated as compared to Lim Chu Kang, its effectiveness may not be worth the cost. Fences can also be set up if so desired, but since the area is on military land the risk of trespassers is far lower.</p>
<p>Seeing that photovoltaic farms require minimal maintenance, and individual panels are rated to last several decades before replacement, the impact of maintenance on a potential solar farm in this military-cordoned area should not be much of a concern.</p>
</section>
<section id="murai-subzone" class="level1">
<h1>Murai Subzone</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./assets/analysis_5.png" class="img-fluid figure-img"></p>
<figcaption>Fig 1.6</figcaption>
</figure>
</div>
<p>Another area we considered is this corner of the Murai Subzone. Particularly, we extracted out the land use patterns for this to highlight the potential of this plot of land for agrivoltaic usage (dual-use land for agriculture and solar farm). As can be observed from this visualisation, a majority of the land here is allocated for agriculture. However, this agricultural land is far from contiguously spaced, with many buildings and roads interspersed within. This follows the same land usage distribution for the Lim Chu Kang agrivoltaic potential zone, and as such, our recommendations for a potential agrivoltaic solar farm for this area should follow the same recommended guidelines as specified for Lim Chu Kang.</p>
<p>Solar Farm Estimations and Calculations From the solar irradiation data, the numbers we obtained are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total Irradiation in 2020 (kWh/m²)</td>
<td>1680</td>
</tr>
<tr class="even">
<td>Average Solar Panel Efficiency (%)</td>
<td>20</td>
</tr>
<tr class="odd">
<td>DC to AC Conversion Factor</td>
<td>1.29</td>
</tr>
</tbody>
</table>
<p>Solar panel efficiency was derived from Google searches.</p>
<p>Since solar panels generate DC electricity, and appliances use AC, we calculate the conversion by referring to Chapter 6.1 in SES 2024: * P = average of “inst_cap_mwp” * AC = average of “inst_cap_mwac” * Conversion Factor = P / AC</p>
<p>Calculate the total power output per m2 annually to be 0.2 * 1680 = 336 kWh DC.</p>
<p>Converting the output into AC, 336 / 1.29 = 260.4 kWh AC.</p>
<p>Hence, 1m2 of solar panel coverage can provide 260.4 kWh AC of power annually.</p>
<p>Before merging these numbers with the total area within our target regions, we need to keep in mind that it is not possible to achieve 100% solar panel coverage for any piece of land.</p>
<ul>
<li>About 40-60% of open land is usable for solar panel deployment. We decided to take a conservative estimate of 45%.</li>
<li>An aquatic solar farm exists at Tengeh reservoir. About 35% of the reservoir is used for that. We decided to follow it.</li>
<li>On average, the coverage of solar farms in agrivoltaics farms is around 10-50%. We decided to take the average of that.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 23%">
<col style="width: 20%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Lim Chu Kang (Open Space)</th>
<th>Reservoirs (Floating)</th>
<th>Murai (Agrivoltaics)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total Area (m²)</td>
<td>4 691 840</td>
<td>7 774 950</td>
<td>5 046 540</td>
</tr>
<tr class="even">
<td>Total Annual AC (kWh)</td>
<td>1 221 877 136</td>
<td>2 024 280 780</td>
<td>1 314 133 416</td>
</tr>
<tr class="odd">
<td>Solar Panel Coverage (%)</td>
<td>45</td>
<td>35</td>
<td>30</td>
</tr>
<tr class="even">
<td><strong>Overall Annual AC Provided (kWh)</strong></td>
<td><strong>549 844 711.2</strong></td>
<td><strong>708 498 273.0</strong></td>
<td><strong>394 240 024.8</strong></td>
</tr>
</tbody>
</table>
<p>From the results, we determined that Lim Chu Kang and the reservoirs would boast the greatest cost-benefit ratio for energy production.. * Leveraging open, mostly unallocated space is the most feasible avenue to deploy scalable solar farms. Additionally, it does not compete with the scarce land that Murai has. * As mentioned above, a solar farm already exists at Tengeh reservoir, which is an excellent proof of concept. By following its implementations and improving upon them, deploying solar farms in surrounding reservoirs has a high likelihood of success.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>